spring:

  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/wishlist
    driver-class-name: org.postgresql.Driver
    username: wishlist_admin
    password: Cloud_123

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    username:
    password:
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

  security:
   oauth2:
     client:
       registration:
         facebook:
           clientId:
           clientSecret:
           scope:
             - email
             - public_profile


  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html

jwt:
  secret: secret

-Demail:
  activation-base-url: http:\\localhost:8080