spring:

  datasource:
    url: jdbc:sqlserver://localhost:1433;DatabaseName=wishlist
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: Password123

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.SQLServer2012Dialect

  mail:
    host: smtp.gmail.com
    username: b.gerashchencko@gmail.com
    password: huj153153
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true

  security:
    oauth2:
      resource:
        filter-order: 3

-Demail:
  activation-base-url: http:\\localhost:8080